from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from specromancy.contracts import RESERVED_COMMANDS
from specromancy.hashing import sha256_bytes


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "adapters" / "manifest.json"


class AdapterDriftContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    def test_checked_in_adapters_have_no_drift(self) -> None:
        result = subprocess.run(
            [str(ROOT / "bin" / "specromancy"), "adapters", "generate", "--check"],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("up to date", result.stdout)

    def test_modified_generated_adapter_fails_check_without_rewriting(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            for relative in ("AGENTS.md", "specromancy", ".agents", "adapters"):
                source = ROOT / relative
                destination = root / relative
                if source.is_dir():
                    shutil.copytree(source, destination)
                else:
                    shutil.copy2(source, destination)
            for directory in (".claude", ".github", ".opencode"):
                shutil.copytree(ROOT / directory, root / directory)
            changed = root / ".opencode" / "commands" / "specromancy-status.md"
            changed.write_text(changed.read_text(encoding="utf-8") + "drift\n", encoding="utf-8")
            before = changed.read_bytes()
            result = subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "specromancy",
                    "--root",
                    str(root),
                    "--pipeline",
                    str(root / "specromancy" / "pipeline.toml"),
                    "adapters",
                    "generate",
                    "--check",
                ],
                cwd=ROOT,
                check=False,
                capture_output=True,
                text=True,
            )
            self.assertEqual(result.returncode, 11)
            self.assertIn("drift", result.stderr)
            self.assertEqual(changed.read_bytes(), before)

    def test_manifest_covers_all_harnesses_and_matches_bytes(self) -> None:
        targets = {entry["name"]: entry for entry in self.manifest["targets"]}
        self.assertEqual(
            set(targets), {"claude", "codex", "copilot", "hermes", "opencode"}
        )
        self.assertEqual(targets["codex"]["mode"], "native")
        self.assertEqual(targets["codex"]["paths"], [])
        self.assertEqual(targets["hermes"]["mode"], "native")
        self.assertEqual(targets["hermes"]["paths"], [])
        for entry in self.manifest["generated"]:
            content = (ROOT / entry["path"]).read_bytes()
            self.assertEqual(entry["sha256"], sha256_bytes(content), entry["path"])

    def test_generated_text_has_provenance_and_valid_skill_frontmatter(self) -> None:
        for entry in self.manifest["generated"]:
            path = ROOT / entry["path"]
            text = path.read_text(encoding="utf-8")
            with self.subTest(path=entry["path"]):
                self.assertIn("Generated by Specromancy", text[:300])
                self.assertIn("Canonical source:", text[:400])
                self.assertIn("bin/specromancy adapters generate", text[:500])
                if path.name == "SKILL.md":
                    self.assertTrue(text.startswith("---\n# Generated"))

    def test_wrappers_reference_only_existing_commands_and_skills(self) -> None:
        canonical_skills = {
            path.parent.name for path in (ROOT / ".agents" / "skills").glob("*/SKILL.md")
        }
        mirrored_skills = {
            path.parent.name for path in (ROOT / ".claude" / "skills").glob("*/SKILL.md")
        }
        self.assertEqual(mirrored_skills, canonical_skills)
        wrapper_paths = [
            ROOT / entry["path"]
            for entry in self.manifest["generated"]
            if "commands/" in entry["path"] or entry["path"].endswith(".prompt.md")
        ]
        for path in wrapper_paths:
            text = path.read_text(encoding="utf-8")
            commands = re.findall(r"bin/specromancy\s+([a-z-]+)", text)
            with self.subTest(path=path.relative_to(ROOT)):
                self.assertEqual(len(commands), 2)
                self.assertIn(commands[-1], RESERVED_COMMANDS)

        self.assertIn(
            'phase "$0" "$1"',
            (ROOT / ".claude/commands/specromancy/phase.md").read_text(
                encoding="utf-8"
            ),
        )
        opencode = (ROOT / ".opencode/commands/specromancy-phase.md").read_text(
            encoding="utf-8"
        )
        self.assertIn('phase "$1" "$2"', opencode)
        self.assertNotIn("argument-hint:", opencode)
        copilot = (
            ROOT / ".github/prompts/specromancy-phase.prompt.md"
        ).read_text(encoding="utf-8")
        self.assertIn("argument-hint: RUN_ID PHASE", copilot)
        self.assertIn("agent: agent", copilot)

    def test_generated_adapters_contain_no_workflow_logic(self) -> None:
        forbidden = (
            "[[phases.transitions]]",
            "max_traversals",
            "approval_conditions",
            "stop_conditions =",
            "validator =",
            "terminal_outcomes",
        )
        for entry in self.manifest["generated"]:
            text = (ROOT / entry["path"]).read_text(encoding="utf-8")
            with self.subTest(path=entry["path"]):
                for marker in forbidden:
                    self.assertNotIn(marker, text)


if __name__ == "__main__":
    unittest.main()
