"""Deterministic, repository-confined harness adapter generation."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import stat
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Protocol

from .. import __version__
from ..compatibility import ADAPTER_MANIFEST_VERSION, require_supported_version
from ..errors import SafetyError, ValidationError
from ..io import atomic_write_json, atomic_write_text, normalized_text
from ..paths import RepositoryPaths
from ..security import validate_canonical_skills


ADAPTER_MANIFEST_PATH = "specromancy/adapters/manifest.json"
CANONICAL_SKILLS = ("pipeline", "research", "plan", "implement", "review")
GENERATED_MARKER = "Generated by Specromancy"
BACKUP_ROOT = "specromancy/adapters/backups"


def _digest_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _file_digest(path: Path) -> str:
    try:
        return _digest_bytes(path.read_bytes())
    except OSError as exc:
        raise ValidationError(f"Could not read adapter file {path}.", path=str(path)) from exc


def _normalized_bytes(path: Path) -> bytes:
    try:
        data = path.read_bytes()
    except OSError as exc:
        raise ValidationError(f"Could not read canonical source {path}.", path=str(path)) from exc
    try:
        return normalized_text(data.decode("utf-8")).encode("utf-8")
    except UnicodeDecodeError:
        return data


def generated_header(harness: str, sources: Iterable[str]) -> str:
    joined = ", ".join(sources)
    return (
        f"<!-- {GENERATED_MARKER} adapter '{harness}' v1. "
        f"Sources: {joined}. DO NOT EDIT; run `specromancy adapters generate`. -->\n\n"
    )


def add_markdown_header(content: str, header: str) -> str:
    """Insert provenance after YAML frontmatter without changing that frontmatter."""

    text = normalized_text(content)
    if not text.startswith("---\n"):
        return header + text
    closing = text.find("\n---\n", 4)
    if closing < 0:
        return header + text
    boundary = closing + len("\n---\n")
    return text[:boundary] + "\n" + header + text[boundary:]


@dataclass(frozen=True)
class GeneratedFile:
    """One complete output owned by a harness adapter."""

    path: str
    harness: str
    adapter_version: int
    sources: tuple[str, ...]
    transformation: str
    content: bytes
    mode: int = 0o644
    committed: bool = True
    minimum_harness_version: str | None = None

    @classmethod
    def text(
        cls,
        *,
        path: str,
        harness: str,
        sources: Iterable[str],
        transformation: str,
        content: str,
        mode: int = 0o644,
        adapter_version: int = 1,
        minimum_harness_version: str | None = None,
    ) -> "GeneratedFile":
        return cls(
            path=path,
            harness=harness,
            adapter_version=adapter_version,
            sources=tuple(sources),
            transformation=transformation,
            content=normalized_text(content).encode("utf-8"),
            mode=mode,
            minimum_harness_version=minimum_harness_version,
        )

    @property
    def sha256(self) -> str:
        return _digest_bytes(self.content)


class Adapter(Protocol):
    name: str
    version: int
    native: bool
    minimum_harness_version: str | None

    def render(self, root: Path) -> tuple[GeneratedFile, ...]: ...

    def validate_sources(self, root: Path) -> None: ...

    def managed_candidates(self, root: Path) -> tuple[Path, ...]: ...


class AdapterBase:
    name = ""
    version = 1
    native = False
    minimum_harness_version: str | None = None

    def validate_sources(self, root: Path) -> None:
        canonical_sources(root)

    def managed_candidates(self, root: Path) -> tuple[Path, ...]:
        return ()


class NativeAdapter(AdapterBase):
    native = True

    def render(self, root: Path) -> tuple[GeneratedFile, ...]:
        self.validate_sources(root)
        return ()


def _validate_skill_frontmatter(path: Path, expected_name: str) -> None:
    text = normalized_text(path.read_text(encoding="utf-8"))
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValidationError(
            f"Canonical skill '{expected_name}' has no YAML frontmatter.", path=str(path)
        )
    try:
        closing = lines.index("---", 1)
    except ValueError as exc:
        raise ValidationError(
            f"Canonical skill '{expected_name}' has unclosed YAML frontmatter.",
            path=str(path),
        ) from exc
    metadata: dict[str, str] = {}
    for line in lines[1:closing]:
        key, separator, value = line.partition(":")
        if separator and key in {"name", "description"}:
            if key in metadata:
                raise ValidationError(
                    f"Canonical skill '{expected_name}' repeats '{key}'.", path=str(path)
                )
            metadata[key] = value.strip().strip('"\'')
    if metadata.get("name") != expected_name or not metadata.get("description"):
        raise ValidationError(
            f"Canonical skill '{expected_name}' is not discoverable.",
            path=str(path),
            hint=(
                f"Set non-empty 'name: {expected_name}' and 'description:' fields "
                "in SKILL.md frontmatter."
            ),
        )


def canonical_sources(root: Path) -> tuple[Path, tuple[Path, ...]]:
    agents = root / "AGENTS.md"
    if not agents.is_file():
        raise ValidationError(
            "Canonical AGENTS.md is missing.",
            path=str(agents),
            hint="Create the canonical project instructions before generating adapters.",
        )
    skills = validate_canonical_skills(root, CANONICAL_SKILLS)
    return agents, skills


def _portable_source_mode(root: Path, source: Path) -> int:
    """Prefer Git's cross-platform executable bit, with a filesystem fallback."""

    relative = RepositoryPaths(root).serialize(source)
    try:
        completed = subprocess.run(
            ["git", "ls-files", "--stage", "--", relative],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
    except OSError:
        completed = None
    if completed is not None and completed.returncode == 0 and completed.stdout.strip():
        git_mode = completed.stdout.split(maxsplit=1)[0]
        return 0o755 if git_mode == "100755" else 0o644
    source_mode = stat.S_IMODE(source.stat().st_mode)
    return 0o755 if source_mode & 0o111 else 0o644


def copy_skill_outputs(root: Path, harness: str) -> tuple[GeneratedFile, ...]:
    """Render all canonical Claude skill copies in deterministic path order."""

    _, skills = canonical_sources(root)
    outputs: list[GeneratedFile] = []
    paths = RepositoryPaths(root)
    for skill_file in skills:
        skill_dir = skill_file.parent
        for source in sorted((p for p in skill_dir.rglob("*") if p.is_file()), key=lambda p: p.as_posix()):
            if source.is_symlink():
                raise SafetyError(
                    "Canonical skill trees may not contain symlinked files.", path=str(source)
                )
            relative_in_skill = source.relative_to(skill_dir)
            source_relative = paths.serialize(source)
            destination = Path(".claude/skills") / skill_dir.name / relative_in_skill
            content = _normalized_bytes(source)
            if source.suffix.lower() == ".md":
                text = content.decode("utf-8")
                text = add_markdown_header(
                    text, generated_header(harness, (source_relative,))
                )
                content = text.encode("utf-8")
            mode = _portable_source_mode(root, source)
            outputs.append(
                GeneratedFile(
                    path=destination.as_posix(),
                    harness=harness,
                    adapter_version=1,
                    sources=(source_relative,),
                    transformation="normalized-copy-with-provenance",
                    content=content,
                    mode=mode,
                )
            )
    return tuple(outputs)


def _source_records(root: Path, output: GeneratedFile) -> list[dict[str, str]]:
    paths = RepositoryPaths(root)
    records: list[dict[str, str]] = []
    for source in output.sources:
        target = paths.resolve_relative(source)
        if not target.is_file():
            raise ValidationError("Adapter source is missing.", path=source)
        records.append({"path": source, "sha256": _digest_bytes(_normalized_bytes(target))})
    return records


def _manifest_record(root: Path, output: GeneratedFile) -> dict[str, Any]:
    return {
        "adapter": output.harness,
        "adapter_version": output.adapter_version,
        "committed": output.committed,
        "minimum_harness_version": output.minimum_harness_version,
        "mode": f"{output.mode:04o}",
        "path": output.path,
        "sha256": output.sha256,
        "sources": _source_records(root, output),
        "transformation": output.transformation,
    }


def _adapter_metadata(adapters: Iterable[Adapter]) -> dict[str, dict[str, Any]]:
    return {
        adapter.name: {
            "minimum_harness_version": adapter.minimum_harness_version,
            "native": adapter.native,
            "version": adapter.version,
        }
        for adapter in sorted(adapters, key=lambda item: item.name)
    }


def _new_manifest(adapters: Iterable[Adapter], files: Iterable[dict[str, Any]]) -> dict[str, Any]:
    return {
        "schema_version": ADAPTER_MANIFEST_VERSION,
        "generated_by": f"specromancy {__version__}",
        "adapters": _adapter_metadata(adapters),
        "files": sorted(files, key=lambda item: item["path"]),
    }


def _load_manifest(root: Path, *, required: bool) -> dict[str, Any] | None:
    target = root / ADAPTER_MANIFEST_PATH
    if not target.is_file():
        if required:
            raise ValidationError(
                "Adapter manifest is missing.",
                path=ADAPTER_MANIFEST_PATH,
                hint="Run `specromancy adapters generate`.",
            )
        return None
    try:
        value = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValidationError(
            "Adapter manifest is not valid JSON.", path=ADAPTER_MANIFEST_PATH
        ) from exc
    if not isinstance(value, dict):
        raise ValidationError(
            "Adapter manifest version is unsupported.", path=ADAPTER_MANIFEST_PATH
        )
    try:
        require_supported_version(
            "Adapter manifest", value.get("schema_version"), ADAPTER_MANIFEST_VERSION
        )
    except ValidationError as exc:
        raise ValidationError(
            "Adapter manifest version is unsupported.", path=ADAPTER_MANIFEST_PATH
        ) from exc
    files = value.get("files")
    if not isinstance(files, list) or any(not isinstance(row, dict) for row in files):
        raise ValidationError(
            "Adapter manifest files must be a list of records.", path=ADAPTER_MANIFEST_PATH
        )
    seen: set[str] = set()
    for row in files:
        path = row.get("path")
        if not isinstance(path, str) or path in seen:
            raise ValidationError(
                "Adapter manifest contains an invalid or duplicate path.",
                path=ADAPTER_MANIFEST_PATH,
            )
        RepositoryPaths(root).resolve_relative(path)
        seen.add(path)
    return value


def _backup_path(root: Path, relative: str, digest: str) -> Path:
    safe_relative = Path(relative)
    return RepositoryPaths(root).resolve_relative(
        (Path(BACKUP_ROOT) / digest / safe_relative).as_posix()
    )


def _write_output(root: Path, output: GeneratedFile) -> None:
    target = RepositoryPaths(root).resolve_relative(output.path)
    target.parent.mkdir(parents=True, exist_ok=True)
    descriptor = -1
    temporary: Path | None = None
    try:
        try:
            text = output.content.decode("utf-8")
        except UnicodeDecodeError:
            descriptor, raw_temporary = tempfile.mkstemp(
                prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
            )
            temporary = Path(raw_temporary)
            with os.fdopen(descriptor, "wb") as handle:
                descriptor = -1
                handle.write(output.content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, target)
            temporary = None
        else:
            atomic_write_text(target, text)
        os.chmod(target, output.mode)
    except (OSError, UnicodeError) as exc:
        raise ValidationError("Could not write generated adapter file.", path=output.path) from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary is not None:
            try:
                temporary.unlink()
            except OSError:
                pass


def generate_adapters(
    root: Path,
    adapters: tuple[Adapter, ...],
    *,
    selected: tuple[Adapter, ...],
    force: bool = False,
) -> dict[str, Any]:
    """Generate selected adapters after an all-or-nothing collision preflight."""

    root = root.resolve()
    paths = RepositoryPaths(root)
    invalid_manifest_backup: tuple[Path, Path] | None = None
    try:
        old_manifest = _load_manifest(root, required=False)
    except ValidationError:
        manifest_target = paths.resolve_relative(ADAPTER_MANIFEST_PATH)
        if not force or not manifest_target.is_file():
            raise
        digest = _file_digest(manifest_target)
        invalid_manifest_backup = (
            manifest_target,
            _backup_path(root, ADAPTER_MANIFEST_PATH, digest),
        )
        old_manifest = None
    old_records = {
        row["path"]: row for row in (old_manifest or {}).get("files", [])
    }
    outputs: list[GeneratedFile] = []
    for adapter in selected:
        outputs.extend(adapter.render(root))
    output_paths = [output.path for output in outputs]
    if len(output_paths) != len(set(output_paths)):
        raise ValidationError("Two adapters attempted to generate the same path.")

    collisions: list[str] = []
    backups: list[tuple[Path, Path]] = (
        [invalid_manifest_backup] if invalid_manifest_backup is not None else []
    )
    selected_names = {adapter.name for adapter in selected}
    rendered_paths = set(output_paths)
    obsolete = [
        row
        for path, row in old_records.items()
        if row.get("adapter") in selected_names and path not in rendered_paths
    ]
    for output in outputs:
        target = paths.resolve_relative(output.path)
        if not target.exists() or not target.is_file():
            if target.exists():
                collisions.append(output.path)
            continue
        current = _file_digest(target)
        old = old_records.get(output.path)
        owned = old is not None and current == old.get("sha256")
        if current == output.sha256 or owned:
            continue
        if not force:
            collisions.append(output.path)
            continue
        backup = _backup_path(root, output.path, current)
        backups.append((target, backup))

    for row in obsolete:
        target = paths.resolve_relative(row["path"])
        if not target.exists():
            continue
        if not target.is_file():
            collisions.append(row["path"])
            continue
        current = _file_digest(target)
        if current == row.get("sha256"):
            continue
        if not force:
            collisions.append(row["path"])
            continue
        backups.append((target, _backup_path(root, row["path"], current)))

    manifest_target = paths.resolve_relative(ADAPTER_MANIFEST_PATH)
    if (
        manifest_target.exists()
        and old_manifest is None
        and invalid_manifest_backup is None
    ):
        collisions.append(ADAPTER_MANIFEST_PATH)
    if collisions:
        raise SafetyError(
            "Adapter generation would overwrite user-authored or modified files.",
            hint="Move the files, restore generated content, or rerun with --force to back them up.",
            details={"collisions": sorted(set(collisions))},
        )

    for source, backup in backups:
        backup.parent.mkdir(parents=True, exist_ok=True)
        if not backup.exists():
            try:
                shutil.copy2(source, backup)
            except OSError as exc:
                raise ValidationError(
                    "Could not preserve a forced-replacement backup.", path=str(backup)
                ) from exc
    for output in outputs:
        _write_output(root, output)

    for row in sorted(obsolete, key=lambda item: item["path"], reverse=True):
        target = paths.resolve_relative(row["path"])
        if target.is_file():
            try:
                target.unlink()
            except OSError as exc:
                raise ValidationError(
                    "Could not remove an obsolete generated adapter file.", path=row["path"]
                ) from exc
            _remove_empty_parents(root, target)

    retained = [
        row for row in old_records.values() if row.get("adapter") not in selected_names
    ]
    records = retained + [_manifest_record(root, output) for output in outputs]
    manifest = _new_manifest(adapters, records)
    atomic_write_json(manifest_target, manifest)
    return {
        "generated": sorted(output_paths),
        "backups": [RepositoryPaths(root).serialize(backup) for _, backup in backups],
        "manifest": ADAPTER_MANIFEST_PATH,
    }


def _record_map(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {row["path"]: row for row in manifest["files"]}


def check_adapters(
    root: Path,
    *,
    selected: tuple[Adapter, ...],
) -> dict[str, Any]:
    root = root.resolve()
    manifest = _load_manifest(root, required=True)
    assert manifest is not None
    selected_names = {adapter.name for adapter in selected}
    records = {
        path: row
        for path, row in _record_map(manifest).items()
        if row.get("adapter") in selected_names
    }
    expected: dict[str, GeneratedFile] = {}
    for adapter in selected:
        adapter.validate_sources(root)
        for output in adapter.render(root):
            expected[output.path] = output

    statuses = {"missing": [], "modified": [], "stale": [], "unexpected": []}
    for path, output in expected.items():
        record = records.get(path)
        target = RepositoryPaths(root).resolve_relative(path)
        if record is None or not target.is_file():
            statuses["missing"].append(path)
            continue
        current_digest = _file_digest(target)
        current_mode = f"{stat.S_IMODE(target.stat().st_mode):04o}"
        mode_modified = os.name != "nt" and current_mode != record.get("mode")
        if current_digest != record.get("sha256") or mode_modified:
            statuses["modified"].append(path)
        if (
            output.sha256 != record.get("sha256")
            or f"{output.mode:04o}" != record.get("mode")
            or _source_records(root, output) != record.get("sources")
        ):
            statuses["stale"].append(path)
    for path in records.keys() - expected.keys():
        statuses["unexpected"].append(path)

    declared = set(_record_map(manifest))
    for adapter in selected:
        for candidate in adapter.managed_candidates(root):
            if not candidate.is_file():
                continue
            relative = RepositoryPaths(root).serialize(candidate)
            if relative in declared:
                continue
            try:
                text = candidate.read_text(encoding="utf-8")
            except (OSError, UnicodeError):
                continue
            if GENERATED_MARKER in text:
                statuses["unexpected"].append(relative)

    statuses = {key: sorted(set(value)) for key, value in statuses.items()}
    if any(statuses.values()):
        raise ValidationError(
            "Generated harness adapters are not current.",
            hint="Run `specromancy adapters generate` after resolving modified-file collisions.",
            details=statuses,
        )
    return {"checked": sorted(expected), "status": "current"}


def _remove_empty_parents(root: Path, target: Path) -> None:
    boundary = root.resolve()
    current = target.parent
    while current != boundary:
        try:
            current.rmdir()
        except OSError:
            break
        current = current.parent


def clean_adapters(
    root: Path,
    adapters: tuple[Adapter, ...],
    *,
    selected: tuple[Adapter, ...],
) -> dict[str, Any]:
    """Remove only byte-matching files declared by the manifest."""

    root = root.resolve()
    manifest = _load_manifest(root, required=True)
    assert manifest is not None
    selected_names = {adapter.name for adapter in selected}
    records = _record_map(manifest)
    chosen = [row for row in records.values() if row.get("adapter") in selected_names]
    mismatched: list[str] = []
    for row in chosen:
        target = RepositoryPaths(root).resolve_relative(row["path"])
        if target.exists() and (not target.is_file() or _file_digest(target) != row.get("sha256")):
            mismatched.append(row["path"])
    if mismatched:
        raise SafetyError(
            "Adapter clean refused to remove modified generated files.",
            hint="Restore them to generated content or move them before cleaning.",
            details={"mismatched": sorted(mismatched)},
        )

    removed: list[str] = []
    for row in sorted(chosen, key=lambda item: item["path"], reverse=True):
        target = RepositoryPaths(root).resolve_relative(row["path"])
        if target.is_file():
            try:
                target.unlink()
            except OSError as exc:
                raise ValidationError("Could not remove generated adapter file.", path=row["path"]) from exc
            removed.append(row["path"])
            _remove_empty_parents(root, target)
    retained = [row for row in records.values() if row.get("adapter") not in selected_names]
    atomic_write_json(root / ADAPTER_MANIFEST_PATH, _new_manifest(adapters, retained))
    return {"removed": sorted(removed), "manifest": ADAPTER_MANIFEST_PATH}
