from __future__ import annotations

import json
import re
import subprocess
import sys
import unittest
from pathlib import Path

from specromancy.adapters import HARNESS_MODES
from specromancy.contracts import RESERVED_COMMANDS
from specromancy.hashing import sha256_bytes


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "adapters" / "manifest.json"


class ShippedAdapterTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.manifest_text = MANIFEST.read_text(encoding="utf-8")
        cls.manifest = json.loads(cls.manifest_text)

    def test_adapter_entry_point_reports_no_checkout_drift(self) -> None:
        result = subprocess.run(
            [sys.executable, str(ROOT / "adapters" / "generate.py"), "--check"],
            cwd=ROOT / "docs" / "poc-v3",
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("up to date", result.stdout)

    def test_manifest_covers_harnesses_and_matches_generated_bytes(self) -> None:
        targets = {entry["name"]: entry for entry in self.manifest["targets"]}
        self.assertEqual(set(targets), set(HARNESS_MODES))
        generated_by_target = {name: [] for name in HARNESS_MODES}
        for entry in self.manifest["generated"]:
            self.assertIn(entry["target"], targets)
            generated_by_target[entry["target"]].append(entry["path"])
            content = (ROOT / entry["path"]).read_bytes()
            self.assertEqual(entry["sha256"], sha256_bytes(content), entry["path"])
        for name, mode in HARNESS_MODES.items():
            with self.subTest(target=name):
                self.assertEqual(targets[name]["mode"], mode)
                self.assertEqual(targets[name]["paths"], generated_by_target[name])

    def test_generated_files_have_provenance_and_no_embedded_checkout_data(self) -> None:
        absolute = re.compile(r"(?:^|[\s'\"`(])/(?:Users|home|private|tmp)/")
        timestamp = re.compile(r"\b20\d{2}-\d{2}-\d{2}T\d{2}:\d{2}")
        workflow_markers = (
            "[[phases.transitions]]",
            "approval_conditions =",
            "max_traversals =",
            "stop_conditions =",
            "terminal_outcomes =",
            "validator =",
        )
        self.assertNotIn("timestamp", self.manifest_text.lower())
        self.assertIsNone(absolute.search(self.manifest_text))
        for entry in self.manifest["generated"]:
            path = ROOT / entry["path"]
            text = path.read_text(encoding="utf-8")
            with self.subTest(path=entry["path"]):
                self.assertIn("Generated by Specromancy", text[:300])
                self.assertIn("Canonical source:", text[:400])
                self.assertIn("bin/specromancy adapters generate", text[:500])
                self.assertIsNone(absolute.search(text))
                self.assertIsNone(timestamp.search(text))
                self.assertFalse(any(marker in text for marker in workflow_markers))
                if path.name == "SKILL.md":
                    self.assertTrue(text.startswith("---\n# Generated"))

    def test_wrappers_match_shipped_skills_and_supported_commands(self) -> None:
        canonical = {
            path.parent.name for path in (ROOT / ".agents" / "skills").glob("*/SKILL.md")
        }
        mirrored = {
            path.parent.name for path in (ROOT / ".claude" / "skills").glob("*/SKILL.md")
        }
        self.assertEqual(mirrored, canonical)
        wrappers = [
            ROOT / entry["path"]
            for entry in self.manifest["generated"]
            if "commands/" in entry["path"] or entry["path"].endswith(".prompt.md")
        ]
        for path in wrappers:
            commands = re.findall(
                r"bin/specromancy\s+([a-z-]+)", path.read_text(encoding="utf-8")
            )
            with self.subTest(path=path.relative_to(ROOT)):
                self.assertEqual(len(commands), 2)
                self.assertIn(commands[-1], RESERVED_COMMANDS)


if __name__ == "__main__":
    unittest.main()
