"""Deterministic public-API scenarios for the pre-extraction baseline.

Expected records are checked in, never regenerated by tests. All writes here
belong to temporary fixture repositories, including interrupted commits.
"""

from __future__ import annotations

import json
import io
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

from specromancy.cli import main
from specromancy.config import PipelineConfigError, canonicalize_pipeline, load_pipeline
from specromancy.engine import Engine
from specromancy.run_store import RunStore


FIXTURES = Path(__file__).resolve().parents[1] / "fixtures/refactoring-compatibility"
NOW = datetime(2026, 10, 3, 12, 0, 0, tzinfo=timezone.utc)
RUN_ID = "20261003T120000Z-01020304"


class InterruptedCommit(RuntimeError):
    pass


class CompatibilityFixture:
    def __init__(self, *, pause: bool | None = None) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name).resolve()
        shutil.copytree(FIXTURES / "source", self.root, dirs_exist_ok=True)
        self.path = self.root / "workflow/pipelines/compatibility.toml"
        if pause is not None:
            self.path.write_text(
                self.path.read_text(encoding="utf-8").replace(
                    'target = "seal"', f'target = "seal"\npause = {str(pause).lower()}'
                ), encoding="utf-8",
            )
        # Content snapshots include modes; set them instead of hiding them.
        for path in self.root.rglob("*"):
            if path.is_file():
                path.chmod(0o644)
        self.pipeline = load_pipeline(self.path, self.root)
        self.store = self.new_store()
        self.engine = Engine(self.pipeline, self.store)

    def new_store(self, fault_injector=None) -> RunStore:
        return RunStore(
            self.root, clock=lambda: NOW,
            random_source=lambda count: bytes.fromhex("01020304"),
            fault_injector=fault_injector,
        )

    def close(self) -> None:
        self.temporary.cleanup()

    def snapshot(self) -> dict[str, str]:
        directory = self.store.run_directory(RUN_ID)
        return {
            path.relative_to(directory).as_posix(): path.read_text(encoding="utf-8")
            for path in sorted(directory.rglob("*")) if path.is_file()
        }

    def restore(self, files: dict[str, str]) -> None:
        directory = self.store.runs_root / RUN_ID
        directory.mkdir(parents=True)
        for name, content in files.items():
            path = directory / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


def normalize_response(value, root: Path):
    """Only response absolute roots and interpreter paths are machine-specific."""
    if isinstance(value, dict):
        return {key: normalize_response(item, root) for key, item in value.items()}
    if isinstance(value, list):
        return [normalize_response(item, root) for item in value]
    if isinstance(value, str):
        if value == sys.executable:
            return "<PYTHON>"
        return value.replace(str(root), "<ROOT>")
    return value


def capture_canonical() -> dict:
    records = {}
    for name, pause in (("absent", None), ("false", False), ("true", True)):
        fixture = CompatibilityFixture(pause=pause)
        try:
            records[name] = {
                "canonical": canonicalize_pipeline(fixture.pipeline),
                "sha256": fixture.pipeline.config_hash,
            }
        finally:
            fixture.close()
    return records


def capture_lifecycle() -> tuple[dict, dict]:
    states, responses = {}, {}
    fixture = CompatibilityFixture(pause=True)
    try:
        engine, store = fixture.engine, fixture.store
        # Engine approval timestamps currently have no constructor injection.
        # Freeze that existing clock seam without normalizing persisted hashes.
        with patch("specromancy.engine.utc_now", return_value=NOW):
            responses["action-pending"] = engine.initialize("Écrire la preuve 日本語")
            states["pending"] = fixture.snapshot()
            responses["action-active"] = engine.start_phase(RUN_ID, "compose")
            states["active"] = fixture.snapshot()
            store.write_visit_output(RUN_ID, 1, "Evidence: café 日本語\n")
            responses["approval"] = engine.request_approval(
                RUN_ID, reason="accept-result", details="Accept this evidence.",
                outcome="z-next",
            )
            states["awaiting-approval"] = fixture.snapshot()

            def stop_after_grant(point: str) -> None:
                if point == "after-event-append":
                    raise InterruptedCommit("approval granted before advancement")

            interrupted = Engine(fixture.pipeline, fixture.new_store(stop_after_grant))
            try:
                interrupted.approve(RUN_ID, "compose")
            except InterruptedCommit:
                pass
            else:
                raise AssertionError("approval fault was not reached")
            states["approved"] = fixture.snapshot()
            responses["paused"] = engine.approve(RUN_ID, "compose")
            states["paused"] = fixture.snapshot()
            responses["resumed"] = engine.resume(RUN_ID)
            engine.start_phase(RUN_ID, "seal")
            store.write_visit_output(RUN_ID, 2, "Sealed.\n")
            responses["terminal"] = engine.validate(RUN_ID, "seal")
            states["completed"] = fixture.snapshot()
        responses = normalize_response(responses, fixture.root)
    finally:
        fixture.close()

    fixture = CompatibilityFixture(pause=True)
    try:
        fixture.engine.initialize("Écrire la preuve 日本語")

        def stop_after_replace(point: str) -> None:
            if point == "after-manifest-replace":
                raise InterruptedCommit("manifest committed before event append")

        interrupted = Engine(fixture.pipeline, fixture.new_store(stop_after_replace))
        try:
            interrupted.start_phase(RUN_ID, "compose")
        except InterruptedCommit:
            pass
        else:
            raise AssertionError("replacement fault was not reached")
        states["recoverable"] = fixture.snapshot()  # Do not load/recover first.
        fixture.store.load(RUN_ID)
        states["recovered"] = fixture.snapshot()
        with patch("specromancy.engine.utc_now", return_value=NOW):
            responses["blocked"] = normalize_response(
                fixture.engine.block(RUN_ID, reason="no-evidence", details="No source."),
                fixture.root,
            )
    finally:
        fixture.close()
    return states, responses


def read_record(name: str):
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def capture_diagnostics() -> dict:
    fixture = CompatibilityFixture(pause=True)
    try:
        results = {}
        fixture.engine.initialize("Écrire la preuve 日本語")
        fixture.engine.start_phase(RUN_ID, "compose")
        for name, args in (
            ("wrong-phase", ["phase", RUN_ID, "seal"]),
            ("outcome-before-output", ["validate", RUN_ID, "compose"]),
            ("missing-output", ["validate", RUN_ID, "compose", "--outcome", "z-next"]),
        ):
            stdout, stderr = io.StringIO(), io.StringIO()
            code = main(
                ["--root", str(fixture.root), "--json", *args],
                stdout=stdout, stderr=stderr,
            )
            results[name] = {
                "exit_code": code, "stdout": stdout.getvalue(),
                "stderr": json.loads(stderr.getvalue()),
            }
        original = fixture.path.read_text(encoding="utf-8")
        fixture.store.write_visit_output(RUN_ID, 1, "Evidence.\n")
        with patch("specromancy.engine.utc_now", return_value=NOW):
            fixture.engine.request_approval(RUN_ID, reason="accept-result", outcome="z-next")
        fixture.store.write_visit_output(RUN_ID, 1, "Changed evidence.\n")
        fixture.path.write_text(original.replace("Seal the result.", "Seal carefully."), encoding="utf-8")
        stdout, stderr = io.StringIO(), io.StringIO()
        code = main(
            ["--root", str(fixture.root), "--json", "approve", RUN_ID, "compose"],
            stdout=stdout, stderr=stderr,
        )
        results["stale-approval"] = {
            "exit_code": code, "stdout": json.loads(stdout.getvalue()),
            "stderr": stderr.getvalue(),
        }
        for name, old, new in (
            ("field-location", 'mutation = "read-only"', 'mutation = "sometimes"'),
            ("transition-location", 'target = "seal"', 'target = "missing"'),
            ("schema-location", 'validator = "file"',
             'validator = { type = "json", schema = "result.schema.json" }'),
        ):
            (fixture.path.parent / "result.schema.json").write_text(
                '{"type":"object","properties":{"result":{"minLength":1}}}',
                encoding="utf-8",
            )
            fixture.path.write_text(original.replace(old, new, 1), encoding="utf-8")
            try:
                load_pipeline(fixture.path, fixture.root)
            except PipelineConfigError as error:
                results[name] = error.as_dict()
            else:
                raise AssertionError(f"{name} must reject")
        return normalize_response(results, fixture.root)
    finally:
        fixture.close()
