import hashlib
import json
import os
from pathlib import Path
import tempfile
import unittest

from specromancy.adapters import ADAPTERS, check, clean, generate, select_adapters
from specromancy.adapters.base import ADAPTER_MANIFEST_PATH, CANONICAL_SKILLS
from specromancy.errors import SafetyError, ValidationError


SKILL = """---
name: {name}
description: Exercise the {name} phase.
---

# {title}

Read [the policy](references/policy.md), then execute the canonical procedure.
"""


class AdapterTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name).resolve()
        (self.root / "AGENTS.md").write_bytes(b"# Instructions\r\n\r\nKeep policy canonical.\r\n")
        for name in CANONICAL_SKILLS:
            skill = self.root / ".agents" / "skills" / name
            (skill / "references").mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                SKILL.format(name=name, title=name.title()), encoding="utf-8"
            )
            (skill / "references" / "policy.md").write_text(
                f"# {name.title()} policy\n", encoding="utf-8"
            )
        script = self.root / ".agents" / "skills" / "pipeline" / "scripts" / "probe.sh"
        script.parent.mkdir()
        script.write_text("#!/bin/sh\nprintf ok\n", encoding="utf-8")
        script.chmod(0o755)
        binary = self.root / ".agents" / "skills" / "pipeline" / "assets" / "sample.bin"
        binary.parent.mkdir()
        binary.write_bytes(b"\x00\xff\r\n")

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def test_generation_is_deterministic_and_normalizes_text(self) -> None:
        first = generate(self.root)
        manifest = self.root / ADAPTER_MANIFEST_PATH
        first_manifest = manifest.read_bytes()
        first_digests = {
            path: hashlib.sha256((self.root / path).read_bytes()).hexdigest()
            for path in first["generated"]
        }

        second = generate(self.root)

        self.assertEqual(first["generated"], second["generated"])
        self.assertEqual(first_manifest, manifest.read_bytes())
        self.assertEqual(
            first_digests,
            {
                path: hashlib.sha256((self.root / path).read_bytes()).hexdigest()
                for path in second["generated"]
            },
        )
        self.assertNotIn(b"\r", (self.root / "CLAUDE.md").read_bytes())
        self.assertEqual(check(self.root)["status"], "current")

    def test_claude_copy_preserves_references_binary_assets_and_executable_mode(self) -> None:
        generate(self.root, harness="claude")

        copied_skill = self.root / ".claude" / "skills" / "pipeline" / "SKILL.md"
        copied_policy = copied_skill.parent / "references" / "policy.md"
        copied_script = copied_skill.parent / "scripts" / "probe.sh"
        copied_binary = copied_skill.parent / "assets" / "sample.bin"
        self.assertIn("references/policy.md", copied_skill.read_text(encoding="utf-8"))
        self.assertTrue(copied_policy.is_file())
        self.assertTrue(os.access(copied_script, os.X_OK))
        self.assertEqual(copied_binary.read_bytes(), b"\x00\xff\r\n")
        self.assertTrue(copied_skill.read_text(encoding="utf-8").startswith("---\nname:"))

    def test_user_authored_collision_requires_force_and_force_preserves_backup(self) -> None:
        authored = self.root / "CLAUDE.md"
        authored.write_text("# Mine\n", encoding="utf-8")
        with self.assertRaises(SafetyError) as caught:
            generate(self.root, harness="claude")
        self.assertIn("CLAUDE.md", caught.exception.details["collisions"])

        result = generate(self.root, harness="claude", force=True)

        self.assertEqual(len(result["backups"]), 1)
        backup = self.root / result["backups"][0]
        self.assertEqual(backup.read_text(encoding="utf-8"), "# Mine\n")
        self.assertIn("Generated by Specromancy", authored.read_text(encoding="utf-8"))

    def test_check_distinguishes_modified_stale_and_unexpected_outputs(self) -> None:
        generate(self.root)
        prompt = self.root / ".github" / "prompts" / "review.prompt.md"
        prompt.write_text(prompt.read_text(encoding="utf-8") + "edited\n", encoding="utf-8")
        (self.root / ".agents" / "skills" / "plan" / "SKILL.md").write_text(
            SKILL.format(name="plan", title="Changed plan"), encoding="utf-8"
        )
        extra = self.root / ".opencode" / "commands" / "old.md"
        extra.write_text("<!-- Generated by Specromancy -->\n", encoding="utf-8")

        with self.assertRaises(ValidationError) as caught:
            check(self.root)

        details = caught.exception.details
        self.assertIn(".github/prompts/review.prompt.md", details["modified"])
        self.assertIn(".github/prompts/plan.prompt.md", details["stale"])
        self.assertIn(".claude/skills/plan/SKILL.md", details["stale"])
        self.assertIn(".opencode/commands/old.md", details["unexpected"])

    def test_clean_removes_only_matching_declared_files(self) -> None:
        generate(self.root, harness="opencode")
        review = self.root / ".opencode" / "commands" / "review.md"
        review.write_text("user edit\n", encoding="utf-8")
        with self.assertRaises(SafetyError):
            clean(self.root, harness="opencode")
        self.assertTrue(review.is_file())

        generate(self.root, harness="opencode", force=True)
        result = clean(self.root, harness="opencode")

        self.assertEqual(len(result["removed"]), len(CANONICAL_SKILLS))
        self.assertFalse(review.exists())
        manifest = json.loads((self.root / ADAPTER_MANIFEST_PATH).read_text(encoding="utf-8"))
        self.assertEqual(manifest["files"], [])

    def test_launchers_remain_thin_and_forward_opencode_arguments(self) -> None:
        generate(self.root)
        copilot = (self.root / ".github" / "prompts" / "implement.prompt.md").read_text(
            encoding="utf-8"
        )
        opencode = (self.root / ".opencode" / "commands" / "implement.md").read_text(
            encoding="utf-8"
        )
        self.assertIn(".agents/skills/implement/SKILL.md", copilot)
        self.assertNotIn("## Procedure", copilot)
        self.assertIn("$ARGUMENTS", opencode)
        self.assertNotIn("model:", opencode)

    def test_regeneration_removes_only_unmodified_obsolete_outputs(self) -> None:
        generate(self.root, harness="claude")
        canonical = self.root / ".agents" / "skills" / "pipeline" / "assets" / "sample.bin"
        generated = self.root / ".claude" / "skills" / "pipeline" / "assets" / "sample.bin"
        canonical.unlink()

        generate(self.root, harness="claude")

        self.assertFalse(generated.exists())
        self.assertEqual(check(self.root, harness="claude")["status"], "current")

    @unittest.skipIf(os.name == "nt", "Windows does not expose POSIX executable modes")
    def test_check_detects_generated_executable_mode_drift(self) -> None:
        generate(self.root, harness="claude")
        script = self.root / ".claude" / "skills" / "pipeline" / "scripts" / "probe.sh"
        script.chmod(0o644)

        with self.assertRaises(ValidationError) as caught:
            check(self.root, harness="claude")

        self.assertIn(
            ".claude/skills/pipeline/scripts/probe.sh",
            caught.exception.details["modified"],
        )

    def test_codex_and_hermes_are_native_and_generate_no_skill_copy(self) -> None:
        for name in ("codex", "hermes"):
            with self.subTest(harness=name):
                adapter = select_adapters(name)[0]
                self.assertTrue(adapter.native)
                self.assertEqual(adapter.render(self.root), ())

        result = generate(self.root, harness="codex")
        self.assertEqual(result["generated"], [])
        manifest = json.loads((self.root / ADAPTER_MANIFEST_PATH).read_text(encoding="utf-8"))
        self.assertTrue(manifest["adapters"]["codex"]["native"])
        self.assertTrue(manifest["adapters"]["hermes"]["native"])

    def test_native_adapter_rejects_undiscoverable_skill_frontmatter(self) -> None:
        skill = self.root / ".agents" / "skills" / "review" / "SKILL.md"
        skill.write_text("# Missing frontmatter\n", encoding="utf-8")

        with self.assertRaises(ValidationError) as caught:
            generate(self.root, harness="codex")

        self.assertIn("no YAML frontmatter", caught.exception.message)

    def test_manifest_records_required_provenance_fields(self) -> None:
        generate(self.root)
        manifest = json.loads((self.root / ADAPTER_MANIFEST_PATH).read_text(encoding="utf-8"))
        self.assertEqual(manifest["schema_version"], 1)
        for record in manifest["files"]:
            self.assertEqual(
                set(record),
                {
                    "adapter",
                    "adapter_version",
                    "committed",
                    "minimum_harness_version",
                    "mode",
                    "path",
                    "sha256",
                    "sources",
                    "transformation",
                },
            )
            self.assertTrue(record["sources"])

    def test_registry_is_stable(self) -> None:
        self.assertEqual(
            [adapter.name for adapter in ADAPTERS],
            ["claude", "codex", "copilot", "hermes", "opencode"],
        )


if __name__ == "__main__":
    unittest.main()
